# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: true

inheritance: true

reviews:
  high_level_summary_in_walkthrough: true
  auto_apply_labels: true
  poem: true
  finishing_touches:
    simplify:
      enabled: true
    custom:
      - enabled: true
        name: clean up
        instructions: Test

  profile: assertive
  path_instructions:
    - path: "src/**/*.ts"
      instructions: "Focus on architecture and system design."

tone_instructions: "Prioritize scalability and long-term maintainability."

knowledge_base:
  opt_out: true
  automatic_linking_mode: enabled