apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ryanai-system

resources:
  - ryanai-core.yaml
  - ryanai-databases.yaml
  - ryanai-apps.yaml

# Patch all containers in deployment manifests to use local images without pulling remotely
patches:
  - target:
      kind: Deployment
      name: ryanai-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never