import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, MessageSquare, Trash2, Info, Brain, Github, Terminal } from 'lucide-react';
import { modelMeta } from '@/lib/models';
export default function Sidebar({ conversations, activeId, onSelect, onNew, onDelete, onAbout, onMemory, onConsole, onGithub, githubConnected, }) {
    return (_jsxs("div", { className: "h-full glass rounded-2xl flex flex-col overflow-hidden corner-brackets", children: [_jsxs("div", { className: "px-4 py-4 border-b border-cyan-500/15", children: [_jsxs("div", { className: "flex items-center gap-2.5 mb-4", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-9 h-9 rounded-lg bg-gradient-to-br from-cyan-400 to-cyan-600 flex items-center justify-center shadow-lg shadow-cyan-500/30", children: _jsx("span", { className: "font-display font-black text-ink-950 text-sm", children: "R" }) }), _jsx("div", { className: "absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full bg-emerald-400 border-2 border-ink-950 animate-pulse" })] }), _jsxs("div", { children: [_jsx("h1", { className: "font-display font-bold text-cyan-300 text-sm tracking-wider glow-cyan", children: "RYANAI" }), _jsx("p", { className: "text-[10px] text-ink-500 font-mono tracking-widest uppercase", children: "Reasoning Engine" })] })] }), _jsxs("button", { onClick: onNew, className: "w-full flex items-center justify-center gap-2 py-2.5 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 font-medium text-sm btn-glow hover:bg-cyan-500/20 transition-colors", children: [_jsx(Plus, { size: 16, strokeWidth: 2.5 }), "New Thread"] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto px-2 py-2 space-y-1", children: [conversations.length === 0 && (_jsxs("div", { className: "text-center py-12 px-4", children: [_jsx(MessageSquare, { size: 32, className: "mx-auto text-ink-600 mb-3" }), _jsx("p", { className: "text-xs text-ink-500", children: "No threads yet" }), _jsx("p", { className: "text-[10px] text-ink-600 mt-1", children: "Start a new conversation to begin reasoning" })] })), _jsx(AnimatePresence, { children: conversations.map((conv) => (_jsxs(motion.div, { initial: { opacity: 0, x: -10 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -10 }, transition: { duration: 0.2 }, onClick: () => onSelect(conv.id), className: `group flex items-center gap-2.5 px-3 py-2.5 rounded-lg cursor-pointer transition-all ${activeId === conv.id
                                ? 'bg-cyan-500/15 border border-cyan-500/30'
                                : 'hover:bg-ink-800/50 border border-transparent'}`, children: [_jsx(MessageSquare, { size: 14, className: activeId === conv.id ? 'text-cyan-400' : 'text-ink-600' }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: `text-xs truncate ${activeId === conv.id ? 'text-cyan-200' : 'text-ink-300'}`, children: conv.title }), _jsxs("p", { className: "text-[9px] text-ink-600 font-mono mt-0.5", children: [conv.messages.length, " msgs \u00B7 ", modelMeta(conv.model).short] })] }), _jsx("button", { onClick: (e) => {
                                        e.stopPropagation();
                                        onDelete(conv.id);
                                    }, className: "opacity-0 group-hover:opacity-100 text-ink-600 hover:text-rose-400 transition-all", children: _jsx(Trash2, { size: 13 }) })] }, conv.id))) })] }), _jsxs("div", { className: "px-3 py-3 border-t border-cyan-500/15 space-y-1", children: [_jsxs("button", { onClick: onMemory, className: "w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-ink-400 hover:text-cyan-300 hover:bg-cyan-500/10 transition-all text-xs", children: [_jsx(Brain, { size: 15 }), "Memory Vault"] }), _jsxs("button", { onClick: onConsole, className: "w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-ink-400 hover:text-cyan-300 hover:bg-cyan-500/10 transition-all text-xs", children: [_jsx(Terminal, { size: 15 }), "Inference Console"] }), _jsxs("button", { onClick: onGithub, className: "w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-ink-400 hover:text-cyan-300 hover:bg-cyan-500/10 transition-all text-xs", children: [_jsx(Github, { size: 15 }), "GitHub", githubConnected && (_jsx("span", { className: "ml-auto status-dot online" }))] }), _jsxs("button", { onClick: onAbout, className: "w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-ink-400 hover:text-cyan-300 hover:bg-cyan-500/10 transition-all text-xs", children: [_jsx(Info, { size: 15 }), "About RyanAI"] })] })] }));
}
