import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { Activity, Cpu, Zap, Clock, Database, Terminal, Search, Calculator, Brain, Code, CheckCircle2, Loader2, } from 'lucide-react';
import { modelMeta } from '@/lib/models';
export default function TelemetryPanel({ status, steps, sending }) {
    return (_jsxs("div", { className: "h-full glass rounded-2xl flex flex-col overflow-hidden corner-brackets", children: [_jsx("div", { className: "px-4 py-3 border-b border-cyan-500/15", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Activity, { size: 15, className: "text-cyan-400" }), _jsx("h3", { className: "text-xs font-display font-bold text-cyan-300 tracking-wider uppercase", children: "Telemetry" }), _jsx("span", { className: `ml-auto status-dot ${sending ? 'thinking' : 'online'}` })] }) }), _jsxs("div", { className: "flex-1 overflow-y-auto", children: [_jsxs("div", { className: "px-4 py-3 border-b border-cyan-500/10", children: [_jsx("p", { className: "text-[10px] font-mono text-ink-500 uppercase tracking-wider mb-2.5", children: "System Status" }), _jsxs("div", { className: "space-y-2.5", children: [_jsx(Metric, { icon: _jsx(Cpu, { size: 12 }), label: "CPU Load", value: status ? `${status.cpu.toFixed(0)}%` : '—', progress: status?.cpu ?? 0, color: "cyan" }), _jsx(Metric, { icon: _jsx(Database, { size: 12 }), label: "Memory", value: status ? `${status.memory.toFixed(0)}%` : '—', progress: status?.memory ?? 0, color: "emerald" }), _jsx(Metric, { icon: _jsx(Zap, { size: 12 }), label: "Latency", value: status ? `${status.latency}ms` : '—', progress: status ? Math.min(status.latency / 2, 100) : 0, color: "amber" }), _jsx(Metric, { icon: _jsx(Clock, { size: 12 }), label: "Uptime", value: status?.uptime ?? '—', progress: 75, color: "cyan" })] })] }), _jsxs("div", { className: "px-4 py-3 border-b border-cyan-500/10 grid grid-cols-2 gap-3", children: [_jsxs("div", { className: "bg-ink-800/40 rounded-lg p-2.5 border border-cyan-500/10", children: [_jsx("p", { className: "text-[9px] font-mono text-ink-500 uppercase tracking-wider", children: "Tokens In" }), _jsx("p", { className: "text-lg font-display font-bold text-cyan-300 mt-0.5", children: status?.tokensIn?.toLocaleString() ?? '0' })] }), _jsxs("div", { className: "bg-ink-800/40 rounded-lg p-2.5 border border-emerald-500/10", children: [_jsx("p", { className: "text-[9px] font-mono text-ink-500 uppercase tracking-wider", children: "Tokens Out" }), _jsx("p", { className: "text-lg font-display font-bold text-emerald-300 mt-0.5", children: status?.tokensOut?.toLocaleString() ?? '0' })] })] }), _jsxs("div", { className: "px-4 py-3 border-b border-cyan-500/10", children: [_jsx("p", { className: "text-[10px] font-mono text-ink-500 uppercase tracking-wider mb-2", children: "Active Model" }), _jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("div", { className: "w-8 h-8 rounded-lg flex items-center justify-center", style: {
                                            backgroundColor: (status ? modelMeta(status.model).color : '#22d3ee') + '20',
                                            border: `1px solid ${(status ? modelMeta(status.model).color : '#22d3ee')}40`,
                                        }, children: _jsx(Cpu, { size: 14, style: { color: status ? modelMeta(status.model).color : '#22d3ee' } }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs font-medium text-ink-200", children: status ? modelMeta(status.model).label : 'Claude Sonnet 4.6' }), _jsx("p", { className: "text-[10px] text-ink-500", children: status ? modelMeta(status.model).vendor : 'Anthropic' })] })] })] }), _jsxs("div", { className: "px-4 py-3", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Terminal, { size: 12, className: "text-cyan-400" }), _jsx("p", { className: "text-[10px] font-mono text-ink-500 uppercase tracking-wider", children: "Reasoning Trace" }), sending && (_jsx("span", { className: "ml-auto text-[9px] text-cyan-400 font-mono animate-pulse", children: "LIVE" }))] }), steps.length === 0 && !sending && (_jsxs("div", { className: "text-center py-6", children: [_jsx(Terminal, { size: 24, className: "mx-auto text-ink-700 mb-2" }), _jsx("p", { className: "text-[10px] text-ink-600", children: "No trace data yet" }), _jsx("p", { className: "text-[9px] text-ink-700 mt-0.5", children: "Trace appears during reasoning" })] })), _jsx(AnimatePresence, { children: steps.map((step, i) => (_jsx(motion.div, { initial: { opacity: 0, x: 10 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.2 }, className: "mb-2", children: _jsx(TraceStep, { step: step, index: i }) }, step.id))) }), sending && steps.length === 0 && (_jsxs("div", { className: "flex items-center gap-2 text-[10px] text-cyan-400 font-mono", children: [_jsx(Loader2, { size: 12, className: "animate-spin" }), "Initializing reasoning pipeline..."] }))] })] })] }));
}
function Metric({ icon, label, value, progress, color, }) {
    const colors = {
        cyan: { bar: 'bg-cyan-400', text: 'text-cyan-300' },
        emerald: { bar: 'bg-emerald-400', text: 'text-emerald-300' },
        amber: { bar: 'bg-amber-400', text: 'text-amber-300' },
    };
    const c = colors[color];
    return (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "text-ink-500", children: icon }), _jsx("span", { className: "text-[10px] font-mono text-ink-400 flex-1", children: label }), _jsx("span", { className: `text-[10px] font-mono font-medium ${c.text}`, children: value })] }), _jsx("div", { className: "h-1 bg-ink-800/60 rounded-full overflow-hidden", children: _jsx(motion.div, { className: `h-full ${c.bar} rounded-full`, initial: { width: 0 }, animate: { width: `${Math.min(progress, 100)}%` }, transition: { duration: 0.5 } }) })] }));
}
function TraceStep({ step, index }) {
    const icons = {
        web_search: _jsx(Search, { size: 12 }),
        calculator: _jsx(Calculator, { size: 12 }),
        memory_recall: _jsx(Brain, { size: 12 }),
        code_executor: _jsx(Code, { size: 12 }),
    };
    const isResult = step.type === 'tool_result';
    return (_jsxs("div", { className: `flex items-start gap-2 ${isResult ? 'pl-5' : ''}`, children: [_jsx("div", { className: `shrink-0 mt-0.5 ${isResult ? 'text-emerald-400' : 'text-cyan-400'}`, children: isResult ? _jsx(CheckCircle2, { size: 12 }) : icons[step.name] || _jsx(Terminal, { size: 12 }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsxs("span", { className: "text-[10px] font-mono text-ink-500", children: ["#", index + 1] }), _jsx("span", { className: "text-[10px] font-mono text-cyan-300 capitalize", children: step.name.replace('_', ' ') }), !isResult && step.status === 'running' && (_jsx(Loader2, { size: 10, className: "animate-spin text-cyan-400" }))] }), isResult && step.result && (_jsxs("p", { className: "text-[10px] text-ink-400 mt-0.5 leading-relaxed font-mono", children: [step.result.slice(0, 120), step.result.length > 120 ? '...' : ''] })), !isResult && step.args && (_jsxs("p", { className: "text-[9px] text-ink-600 mt-0.5 font-mono", children: ["args: ", JSON.stringify(step.args).slice(0, 80)] }))] })] }));
}
