import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Terminal, Cpu, Database, RefreshCw, ShieldCheck } from 'lucide-react';
import { ChatStream } from '@/components/ChatStream';
import { useAgentStore } from '@/store/agentStore';
export function App() {
    const [activeTab, setActiveTab] = useState('chat');
    const { sessionId, clearSession, activeTool } = useAgentStore();
    return (_jsxs("div", { className: "flex h-screen w-screen bg-neutral-950 text-neutral-100 font-sans overflow-hidden", children: [_jsxs("aside", { className: "w-64 border-r border-neutral-800 bg-neutral-900 flex flex-col justify-between p-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-3 mb-8 px-2", children: [_jsx("div", { className: "w-8 h-8 rounded-lg bg-sky-600 flex items-center justify-center font-bold text-white", children: "R" }), _jsxs("div", { className: "overflow-hidden", children: [_jsx("h1", { className: "font-bold text-sm tracking-wide truncate", children: "RyanAI Platform" }), _jsxs("p", { className: "text-xs text-neutral-400 font-mono truncate", children: ["Session: ", sessionId.slice(0, 8)] })] })] }), _jsxs("nav", { className: "space-y-1", children: [_jsxs("button", { onClick: () => setActiveTab('chat'), className: `w-full flex items-center space-x-3 px-3 py-2.5 rounded-md text-sm font-medium transition-colors ${activeTab === 'chat'
                                            ? 'bg-neutral-800 text-sky-400'
                                            : 'text-neutral-400 hover:bg-neutral-800/50 hover:text-neutral-200'}`, children: [_jsx(Terminal, { className: "w-4 h-4" }), _jsx("span", { children: "Reasoning Stream" })] }), _jsxs("button", { onClick: () => setActiveTab('telemetry'), className: `w-full flex items-center space-x-3 px-3 py-2.5 rounded-md text-sm font-medium transition-colors ${activeTab === 'telemetry'
                                            ? 'bg-neutral-800 text-sky-400'
                                            : 'text-neutral-400 hover:bg-neutral-800/50 hover:text-neutral-200'}`, children: [_jsx(Cpu, { className: "w-4 h-4" }), _jsx("span", { children: "CUDA & Telemetry" })] }), _jsxs("button", { onClick: () => setActiveTab('vector'), className: `w-full flex items-center space-x-3 px-3 py-2.5 rounded-md text-sm font-medium transition-colors ${activeTab === 'vector'
                                            ? 'bg-neutral-800 text-sky-400'
                                            : 'text-neutral-400 hover:bg-neutral-800/50 hover:text-neutral-200'}`, children: [_jsx(Database, { className: "w-4 h-4" }), _jsx("span", { children: "Vector Memory" })] })] })] }), _jsxs("div", { className: "space-y-3 pt-4 border-t border-neutral-800", children: [activeTool && (_jsxs("div", { className: "px-3 py-2 bg-sky-950/40 border border-sky-800/50 rounded text-xs text-sky-300 flex items-center space-x-2", children: [_jsx(ShieldCheck, { className: "w-3.5 h-3.5 animate-pulse" }), _jsxs("span", { className: "truncate", children: ["Tool: ", activeTool] })] })), _jsxs("button", { onClick: clearSession, className: "w-full flex items-center justify-center space-x-2 px-3 py-2 bg-neutral-800 hover:bg-neutral-700 text-neutral-300 rounded text-xs font-medium transition-colors", children: [_jsx(RefreshCw, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Reset Session" })] })] })] }), _jsxs("main", { className: "flex-1 flex flex-col overflow-hidden bg-neutral-950", children: [_jsxs("header", { className: "h-14 border-b border-neutral-800 flex items-center justify-between px-6 bg-neutral-900/50", children: [_jsxs("div", { className: "flex items-center space-x-2 text-xs font-mono text-neutral-400", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-emerald-500 animate-pulse" }), _jsx("span", { children: "Runtime: ONLINE (Port 3000)" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("span", { className: "text-xs text-neutral-400 font-mono", children: "local@ryanai.local" }), _jsx("span", { className: "text-xs text-neutral-500 font-mono", children: "v1.0.0-prod" })] })] }), _jsxs("div", { className: "flex-1 p-6 overflow-hidden", children: [activeTab === 'chat' && _jsx(ChatStream, {}), activeTab === 'telemetry' && (_jsxs("div", { className: "p-6 bg-neutral-900 rounded-lg border border-neutral-800 font-mono text-sm space-y-4", children: [_jsx("h2", { className: "text-sky-400 font-bold", children: "OpenTelemetry & CUDA Engine Diagnostics" }), _jsx("p", { className: "text-neutral-400", children: "Active OpenTelemetry Collector: http://localhost:4318" }), _jsx("p", { className: "text-neutral-400", children: "CUDA Inference Core: Initialized (Device 0)" })] })), activeTab === 'vector' && (_jsxs("div", { className: "p-6 bg-neutral-900 rounded-lg border border-neutral-800 font-mono text-sm space-y-4", children: [_jsx("h2", { className: "text-sky-400 font-bold", children: "pgvector & Redis Semantic Cache" }), _jsx("p", { className: "text-neutral-400", children: "HNSW Index Status: Optimized (vector_cosine_ops)" })] }))] })] })] }));
}
export default App;
